### PR TITLE
docs: typo fix

### PR DESCRIPTION
**Pull request by gh0st**
Fixes small spelling typo.

### CODE REVIEW

**Comment by LarryKlugerDS** [comment]
Thank you @gh0st !
Are you using this pattern with Azure?

**Comment by gh0st** [comment]
> Thank you @gh0st !
> Are you using this pattern with Azure?

Yes I was!

**Comment by LarryKlugerDS** [comment]
Will you be using it in production? Please connect with me on LinkedIn so we can discuss further. https://www.linkedin.com/in/larrykluger/

Thank you!

**Comment by gh0st** [comment]
No unfortunately not. My organization has not yet adopted a cloud presence.

**Pull request merged**
